### ISSUE TITLE
已经在main.js中引入vvui，但是部分组件报错

### ISSUE THREAD

**Issue by DusuWen** [VV-UI/VV-UI#11]
`[Vue warn]: Unknown custom element: <w-skeleton> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
还有，能不能提供一下组件名称

**Comment by DusuWen** [comment]
我知道了，npm上最新版本1.0.4，希望作者更新一下，谢谢

**Comment by muwoo** [comment]
这个组件库因为使用者不是很多，已经很久没有维护了。望见谅
