### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by wxsms** [VV-UI/VV-UI#4]
从知乎来的，跟你做过几乎一样的事情，因此在下有几点建议：

* 缺少 License
* 完善测试
* 配置持续集成，如 Travis CI 或 Circle CI
* 在 Readme 贴上 CI 与 Code coverage 的 badge

以上都可以更好地帮助项目发展。

**Comment by muwoo** [comment]
好的 感谢，也会逐渐完善
