### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by jinnchen** [VV-UI/VV-UI#7]
项目是刚使用 vue-cli 的 webpack-simple 模板建的空项目，只额外安装了 vv-ui ，报错内容指向了`transform-runtime`和`stage-2`两个包。我的项目并没有依赖他们，依赖是存在于 vv-ui 的，不知道为什么不会安装，

一个小问题，安装一节中 npm 安装方式漏写了一个 `-`，现在是：
```
npm install vvui -save
```
一个小建议，使用一节中引入 css 可以不用书写 node_modules路径，可改为
```
import 'vvui/packages/theme-default/lib/index.css'
```

**Comment by muwoo** [comment]
感您的issue，我会排查一下
