### ISSUE TITLE
1.1.0发布

### ISSUE THREAD

**Issue by chenxiaobin** [VV-UI/VV-UI#8]
你好，骨架屏的说明已经发布，但是1.1.0版本是不是还没发布npm？

**Comment by tylerdong** [comment]
你好，我在看你的这个源代码，能留个微信交流吗 ？

**Comment by muwoo** [comment]
@chenxiaobin 恩，很久没有维护了，有兴趣可以直接看看源码，挺简单的。

**Comment by muwoo** [comment]
@tylerdong QQ: 2424880409
